name: Storybook
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      ENABLE_HSTS: "false"
      # bypass unneeded vars validation during CI
      SKIP_ENV_VALIDATION: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js & Install Dependencies
        uses: ./.github/actions/bootstrap

      - name: Build Storybook
        id: build-step
        run: |
          # Define the path and URL
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            export DEST="pr-${{ github.event.number }}"
          else
            export DEST="."
          fi

          if [ "$DEST" == "." ]; then
            PREVIEW_URL="https://$OWNER.github.io/$REPO_NAME/"
          else
            PREVIEW_URL="https://$OWNER.github.io/$REPO_NAME/$DEST/"
          fi

          echo "url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "dest=$DEST" >> $GITHUB_OUTPUT

          npm run storybook:build -- -o ./storybook-static/$DEST
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          keep_files: true 
          publish_branch: gh-pages
